# Generated by Django 3.2.25 on 2025-03-23 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20250322_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='app_usage_frequency',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='improvements_suggested',
            field=models.TextField(default='No suggestions'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='most_useful_features',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='route_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='safety_perception',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
